export const TABS = ['All', 'In Budget', 'Upgraded'];

export const CATEGORIES = [
  {
    id: 1,
    name: 'All',
    image: 'all-icon.svg',
    imageWidth: 35,
    imageHeight: 34,
  },
  {
    id: 2,
    name: 'Gadgets',
    image: 'gadgets-icon.svg',
    imageWidth: 27,
    imageHeight: 34,
  },
  {
    id: 3,
    name: 'Gadgets',
    image: 'gadgets-icon.svg',
    imageWidth: 27,
    imageHeight: 34,
  },
  {
    id: 4,
    name: 'Gadgets',
    image: 'gadgets-icon.svg',
    imageWidth: 27,
    imageHeight: 34,
  },
  {
    id: 5,
    name: 'Camping',
    image: 'camping-icon.svg',
    imageWidth: 35,
    imageHeight: 35,
  },
  {
    id: 6,
    name: 'Garden',
    image: 'garden-icon.svg',
    imageWidth: 37,
    imageHeight: 39,
  },
  {
    id: 7,
    name: 'Home Appliance',
    image: 'home-appliance-icon.svg',
    imageWidth: 32,
    imageHeight: 32,
  },
  {
    id: 8,
    name: 'Home Decor',
    image: 'home-decor-icon.svg',
    imageWidth: 41.25,
    imageHeight: 31.64,
  },
  {
    id: 9,
    name: 'Kids',
    image: 'kids-icon.svg',
    imageWidth: 37,
    imageHeight: 37,
  },
  {
    id: 10,
    name: 'Kids',
    image: 'kids-icon.svg',
    imageWidth: 37,
    imageHeight: 37,
  },
  {
    id: 11,
    name: 'Kitchen',
    image: 'kitchen-icon.svg',
    imageWidth: 36,
    imageHeight: 27,
  },
  {
    id: 12,
    name: 'Sport',
    image: 'sport-icon.svg',
    imageWidth: 42,
    imageHeight: 27,
  },
  {
    id: 13,
    name: 'Voucher',
    image: 'voucher-icon.svg',
    imageWidth: 40,
    imageHeight: 25,
  },
  {
    id: 14,
    name: 'Kids',
    image: 'kids-icon.svg',
    imageWidth: 37,
    imageHeight: 37,
  },
  {
    id: 15,
    name: 'Kids',
    image: 'kids-icon.svg',
    imageWidth: 37,
    imageHeight: 37,
  },
  {
    id: 16,
    name: 'Kitchen',
    image: 'kitchen-icon.svg',
    imageWidth: 36,
    imageHeight: 27,
  },
  {
    id: 17,
    name: 'Sport',
    image: 'sport-icon.svg',
    imageWidth: 42,
    imageHeight: 27,
  },
  {
    id: 18,
    name: 'Voucher',
    image: 'voucher-icon.svg',
    imageWidth: 40,
    imageHeight: 25,
  },
  {
    id: 19,
    name: 'Kids',
    image: 'kids-icon.svg',
    imageWidth: 37,
    imageHeight: 37,
  },
  {
    id: 20,
    name: 'Kitchen',
    image: 'kitchen-icon.svg',
    imageWidth: 36,
    imageHeight: 27,
  },
  {
    id: 21,
    name: 'Sport',
    image: 'sport-icon.svg',
    imageWidth: 42,
    imageHeight: 27,
  },
  {
    id: 22,
    name: 'Voucher',
    image: 'voucher-icon.svg',
    imageWidth: 40,
    imageHeight: 25,
  },
];
