export const CITIES = {
  he: [
    "אבו ג'ווייעד (שבט)",
    'אבו גוש',
    'אבו סנאן',
    'אבו סריחאן (שבט)',
    'אבו עבדון (שבט)',
    'אבו עמאר (שבט)',
    'אבו עמרה (שבט)',
    'אבו קורינאת (שבט)',
    'אבו קרינאת (יישוב)',
    'אבו רובייעה (שבט)',
    'אבו רוקייק (שבט)',
    'אבו תלול',
    'אבטין',
    'אבטליון',
    'אביאל',
    'אביבים',
    'אביגדור',
    'אביגיל',
    'אביחיל',
    'אביטל',
    'אביעזר',
    'אבירים',
    'אבן יהודה',
    'אבן מנחם',
    'אבן ספיר',
    'אבן שמואל',
    'אבני איתן',
    'אבני חפץ',
    'אבנת',
    'אבשלום',
    'אדורה',
    'אדירים',
    'אדמית',
    'אדרת',
    'אודים',
    'אודם',
    'אוהד',
    'אום אל-פחם',
    'אום אל-קוטוף',
    'אום בטין',
    'אומן',
    'אומץ',
    'אופקים',
    'אור הגנוז',
    'אור הנר',
    'אור יהודה',
    'אור עקיבא',
    'אורה',
    'אורות',
    'אורטל',
    'אורים',
    'אורנים',
    'אורנית',
    'אושה',
    'אזור',
    'אחווה',
    'אחוזם',
    'אחוזת ברק',
    'אחיהוד',
    'אחיטוב',
    'אחיסמך',
    'אחיעזר',
    'אטרש (שבט)',
    'איבים',
    'אייל',
    'איילת השחר',
    'אילון',
    'אילות',
    'אילניה',
    'אילת',
    'אירוס',
    'איתמר',
    'איתן',
    'איתנים',
    'אכסאל',
    'אל סייד',
    'אל-עזי',
    'אל-עריאן',
    'אל-רום',
    'אלומה',
    'אלומות',
    'אלון הגליל',
    'אלון מורה',
    'אלון שבות',
    'אלוני אבא',
    'אלוני הבשן',
    'אלוני יצחק',
    'אלונים',
    'אלי-עד',
    'אליאב',
    'אליכין',
    'אליפז',
    'אליפלט',
    'אליקים',
    'אלישיב',
    'אלישמע',
    'אלמגור',
    'אלמוג',
    'אלעד',
    'אלעזר',
    'אלפי מנשה',
    'אלקוש',
    'אלקנה',
    'אמונים',
    'אמירים',
    'אמנון',
    'אמציה',
    'אניעם',
    'אסד (שבט)',
    'אספר',
    'אעבלין',
    'אעצם (שבט)',
    'אפיניש (שבט)',
    'אפיק',
    'אפיקים',
    'אפק',
    'אפרת',
    'ארבל',
    'ארגמן',
    'ארז',
    'אריאל',
    'ארסוף',
    'אשבול',
    'אשבל',
    'אשדוד',
    'אשדות יעקב (איחוד)',
    'אשדות יעקב (מאוחד)',
    'אשחר',
    'אשכולות',
    'אשל הנשיא',
    'אשלים',
    'אשקלון',
    'אשרת',
    'אשתאול',
    'אתגר',
    'באקה אל-גרביה',
    'באר אורה',
    'באר גנים',
    'באר טוביה',
    'באר יעקב',
    'באר מילכה',
    'באר שבע',
    'בארות יצחק',
    'בארותיים',
    'בארי',
    'בוסתן הגליל',
    "בועיינה-נוג'ידאת",
    'בוקעאתא',
    'בורגתה',
    'בחן',
    'בטחה',
    'ביצרון',
    'ביר אל-מכסור',
    "ביר הדאג'",
    'ביריה',
    'בית אורן',
    'בית אל',
    'בית אלעזרי',
    'בית אלפא',
    'בית אריה',
    'בית ברל',
    "בית ג'ן",
    'בית גוברין',
    'בית גמליאל',
    'בית דגן',
    'בית הגדי',
    'בית הלוי',
    'בית הלל',
    'בית העמק',
    'בית הערבה',
    'בית השיטה',
    'בית זיד',
    'בית זית',
    'בית זרע',
    'בית חגלה',
    'בית חורון',
    'בית חירות',
    'בית חלקיה',
    'בית חנן',
    'בית חנניה',
    'בית חשמונאי',
    'בית יהושע',
    'בית יוסף',
    'בית ינאי',
    'בית יצחק-שער חפר',
    'בית לחם הגלילית',
    'בית מאיר',
    'בית נחמיה',
    'בית ניר',
    'בית נקופה',
    'בית עובד',
    'בית עוזיאל',
    'בית עזרא',
    'בית עריף',
    'בית צבי',
    'בית קמה',
    'בית קשת',
    'בית רבן',
    'בית רימון',
    'בית שאן',
    'בית שמש',
    'בית שערים',
    'בית שקמה',
    'ביתן אהרן',
    'ביתר עילית',
    'בלפוריה',
    'בן זכאי',
    'בן עמי',
    'בן שמן (כפר נוער)',
    'בן שמן (מושב)',
    'בני ברק',
    'בני דקלים',
    'בני דרום',
    'בני דרור',
    'בני יהודה',
    'בני נצרים',
    'בני עטרות',
    'בני עי"ש',
    'בני ציון',
    'בני ראם',
    'בניה',
    'בנימינה-גבעת עדה',
    'בסמ"ה',
    'בסמת טבעון',
    'בענה',
    'בצרה',
    'בצת',
    'בקוע',
    'בקעות',
    'בר גיורא',
    'בר יוחאי',
    'ברוכין',
    'ברור חיל',
    'ברוש',
    'ברכה',
    'ברכיה',
    'ברעם',
    'ברק',
    'ברקאי',
    'ברקן',
    'ברקת',
    'בת הדר',
    'בת חן',
    'בת חפר',
    'בת ים',
    'בת עין',
    'בת שלמה',
    "ג'דיידה-מכר",
    "ג'ולס",
    "ג'לג'וליה",
    "ג'נאביב (שבט)",
    "ג'סר א-זרקא",
    "ג'ש (גוש חלב)",
    "ג'ת",
    'גאולי תימן',
    'גאולים',
    'גאליה',
    'גבולות',
    'גבים',
    'גבע',
    'גבע בנימין',
    'גבע כרמל',
    'גבעולים',
    'גבעון החדשה',
    'גבעות בר',
    'גבעות הרואה',
    'גבעות עדן',
    'גבעת אבני',
    'גבעת אלה',
    'גבעת ברנר',
    'גבעת השלושה',
    'גבעת זאב',
    'גבעת ח"ן',
    'גבעת חיים (איחוד)',
    'גבעת חיים (מאוחד)',
    'גבעת יואב',
    'גבעת יערים',
    'גבעת ישעיהו',
    'גבעת כ"ח',
    'גבעת ניל"י',
    'גבעת עוז',
    'גבעת שמואל',
    'גבעת שמש',
    'גבעת שפירא',
    'גבעתי',
    'גבעתיים',
    'גברעם',
    'גבת',
    'גדות',
    'גדיש',
    'גדעונה',
    'גדרה',
    'גונן',
    'גורן',
    'גורנות הגליל',
    'גזית',
    'גזר',
    'גיאה',
    'גיבתון',
    'גיזו',
    'גילון',
    'גילת',
    'גינוסר',
    'גיניגר',
    'גינתון',
    'גיתה',
    'גיתית',
    'גלאון',
    'גלגל',
    'גליל ים',
    'גלעד (אבן יצחק)',
    'גמזו',
    'גן הדרום',
    'גן השומרון',
    'גן חיים',
    'גן יאשיה',
    'גן יבנה',
    'גן נר',
    'גן שורק',
    'גן שלמה',
    'גן שמואל',
    'גנות',
    'גנות הדר',
    'גני הדר',
    'גני טל',
    'גני יוחנן',
    'גני מודיעין',
    'גני עם',
    'גני תקווה',
    'געש',
    'געתון',
    'גפן',
    'גרופית',
    'גשור',
    'גשר',
    'גשר הזיו',
    'גת (קיבוץ)',
    'גת רימון',
    'דאלית אל-כרמל',
    'דבורה',
    'דבוריה',
    'דביר',
    'דברת',
    "דגניה א'",
    "דגניה ב'",
    'דוב"ב',
    'דולב',
    'דור',
    'דורות',
    'דחי',
    'דייר אל-אסד',
    'דייר חנא',
    'דייר ראפאת',
    'דימונה',
    'דישון',
    'דליה',
    'דלתון',
    'דמיידה',
    'דן',
    'דפנה',
    'דקל',
    "דריג'את",
    'האון',
    'הבונים',
    'הגושרים',
    'הדר עם',
    'הוד השרון',
    'הודיה',
    'הודיות',
    'הוואשלה (שבט)',
    'הוזייל (שבט)',
    'הושעיה',
    'הזורע',
    'הזורעים',
    'החותרים',
    'היוגב',
    'הילה',
    'המעפיל',
    'הסוללים',
    'העוגן',
    'הר אדר',
    'הר גילה',
    'הר עמשא',
    'הראל',
    'הרדוף',
    'הרצליה',
    'הררית',
    'ורד יריחו',
    'ורדון',
    'זבארגה (שבט)',
    'זבדיאל',
    'זוהר',
    'זיקים',
    'זיתן',
    'זכרון יעקב',
    'זכריה',
    'זמר',
    'זמרת',
    'זנוח',
    'זרועה',
    'זרזיר',
    'זרחיה',
    "ח'ואלד",
    "ח'ואלד (שבט)",
    'חבצלת השרון',
    'חבר',
    'חברון',
    'חגור',
    'חגי',
    'חגלה',
    'חד-נס',
    'חדיד',
    'חדרה',
    "חוג'ייראת (ד'הרה)",
    'חולדה',
    'חולון',
    'חולית',
    'חולתה',
    'חוסן',
    'חוסנייה',
    'חופית',
    'חוקוק',
    'חורה',
    'חורפיש',
    'חורשים',
    'חזון',
    'חיבת ציון',
    'חיננית',
    'חיפה',
    'חירות',
    'חלוץ',
    'חלץ',
    'חמאם',
    'חמד',
    'חמדיה',
    'חמדת',
    'חמרה',
    'חניאל',
    'חניתה',
    'חנתון',
    'חספין',
    'חפץ חיים',
    'חפצי-בה',
    'חצב',
    'חצבה',
    'חצור הגלילית',
    'חצור-אשדוד',
    'חצרים',
    'חרב לאת',
    'חרוצים',
    'חריש',
    'חרמש',
    'חרשים',
    'חשמונאים',
    'טבריה',
    'טובא-זנגריה',
    'טורעאן',
    'טייבה',
    'טייבה (בעמק)',
    'טירה',
    'טירת יהודה',
    'טירת כרמל',
    'טירת צבי',
    'טל שחר',
    'טל-אל',
    'טללים',
    'טלמון',
    'טמרה',
    'טמרה (יזרעאל)',
    'טנא',
    'טפחות',
    "יאנוח-ג'ת",
    'יבול',
    'יבנאל',
    'יבנה',
    'יגור',
    'יגל',
    'יד בנימין',
    'יד השמונה',
    'יד חנה',
    'יד מרדכי',
    'יד נתן',
    'יד רמב"ם',
    'ידידה',
    'יהוד-מונוסון',
    'יהל',
    'יובל',
    'יובלים',
    'יודפת',
    'יונתן',
    'יושיביה',
    'יזרעאל',
    'יחיעם',
    'יטבתה',
    'ייט"ב',
    'יכיני',
    'ינוב',
    'ינון',
    'יסוד המעלה',
    'יסודות',
    'יסעור',
    'יעד',
    'יעל',
    'יעף',
    'יערה',
    'יפיע',
    'יפית',
    'יפעת',
    'יפתח',
    'יצהר',
    'יציץ',
    'יקום',
    'יקיר',
    'יקנעם (מושבה)',
    'יקנעם עילית',
    'יראון',
    'ירדנה',
    'ירוחם',
    'ירושלים',
    'ירחיב',
    'ירכא',
    'ירקונה',
    'ישע',
    'ישעי',
    'ישרש',
    'יתד',
    'כאבול',
    "כאוכב אבו אל-היג'א",
    'כברי',
    'כדורי',
    'כדיתה',
    'כוכב השחר',
    'כוכב יאיר',
    'כוכב יעקב',
    'כוכב מיכאל',
    'כורזים',
    'כחל',
    'כחלה',
    'כיסופים',
    'כישור',
    'כליל',
    'כלנית',
    'כמאנה',
    'כמהין',
    'כמון',
    'כנות',
    'כנף',
    'כנרת (מושבה)',
    'כנרת (קבוצה)',
    'כסיפה',
    'כסלון',
    'כסרא-סמיע',
    "כעביה-טבאש-חג'אג'רה",
    'כפר אביב',
    'כפר אדומים',
    'כפר אוריה',
    'כפר אחים',
    'כפר ביאליק',
    'כפר ביל"ו',
    'כפר בלום',
    'כפר בן נון',
    'כפר ברא',
    'כפר ברוך',
    'כפר גדעון',
    'כפר גלים',
    'כפר גליקסון',
    'כפר גלעדי',
    'כפר דניאל',
    'כפר האורנים',
    'כפר החורש',
    'כפר המכבי',
    'כפר הנגיד',
    'כפר הנוער הדתי',
    'כפר הנשיא',
    'כפר הס',
    'כפר הרא"ה',
    'כפר הרי"ף',
    'כפר ויתקין',
    'כפר ורבורג',
    'כפר ורדים',
    'כפר זוהרים',
    'כפר זיתים',
    'כפר חב"ד',
    'כפר חושן',
    'כפר חיטים',
    'כפר חיים',
    'כפר חנניה',
    "כפר חסידים א'",
    "כפר חסידים ב'",
    'כפר חרוב',
    'כפר טרומן',
    'כפר יאסיף',
    'כפר ידידיה',
    'כפר יהושע',
    'כפר יונה',
    'כפר יחזקאל',
    'כפר יעבץ',
    'כפר כמא',
    'כפר כנא',
    'כפר מונש',
    'כפר מימון',
    'כפר מל"ל',
    'כפר מנדא',
    'כפר מנחם',
    'כפר מסריק',
    'כפר מצר',
    'כפר מרדכי',
    'כפר נטר',
    'כפר סאלד',
    'כפר סבא',
    'כפר סילבר',
    'כפר סירקין',
    'כפר עבודה',
    'כפר עזה',
    'כפר עציון',
    'כפר פינס',
    'כפר קאסם',
    'כפר קיש',
    'כפר קרע',
    'כפר ראש הנקרה',
    'כפר רוזנואלד (זרעית)',
    'כפר רופין',
    'כפר רות',
    'כפר שמאי',
    'כפר שמואל',
    'כפר שמריהו',
    'כפר תבור',
    'כפר תפוח',
    'כרי דשא',
    'כרכום',
    'כרם ביבנה (ישיבה)',
    'כרם בן זמרה',
    'כרם בן שמן',
    'כרם מהר"ל',
    'כרם שלום',
    'כרמי יוסף',
    'כרמי צור',
    'כרמי קטיף',
    'כרמיאל',
    'כרמיה',
    'כרמים',
    'כרמל',
    'לבון',
    'לביא',
    'לבנים',
    'להב',
    'להבות הבשן',
    'להבות חביבה',
    'להבים',
    'לוד',
    'לוזית',
    'לוחמי הגיטאות',
    'לוטם',
    'לוטן',
    'לימן',
    'לכיש',
    'לפיד',
    'לפידות',
    'לקיה',
    'מאור',
    'מאיר שפיה',
    'מבוא ביתר',
    'מבוא דותן',
    'מבוא חורון',
    'מבוא חמה',
    'מבוא מודיעים',
    'מבואות ים',
    'מבואות יריחו',
    'מבועים',
    'מבטחים',
    'מבקיעים',
    'מבשרת ציון',
    "מג'ד אל-כרום",
    "מג'דל שמס",
    'מגאר',
    'מגדים',
    'מגדל',
    'מגדל העמק',
    'מגדל עוז',
    'מגדלים',
    'מגידו',
    'מגל',
    'מגן',
    'מגן שאול',
    'מגשימים',
    'מדרך עוז',
    'מדרשת בן גוריון',
    'מדרשת רופין',
    'מודיעין עילית',
    'מודיעין-מכבים-רעות',
    'מולדת',
    'מוצא עילית',
    'מוקייבלה',
    'מורן',
    'מורשת',
    'מזור',
    'מזכרת בתיה',
    'מזרע',
    'מזרעה',
    'מחולה',
    'מחנה הילה',
    'מחנה טלי',
    'מחנה יהודית',
    'מחנה יוכבד',
    'מחנה יפה',
    'מחנה יתיר',
    'מחנה מרים',
    'מחנה תל נוף',
    'מחניים',
    'מחסיה',
    'מטולה',
    'מטע',
    'מי עמי',
    'מיטב',
    'מיטל',
    'מייסר',
    'מיצר',
    'מירב',
    'מירון',
    'מישר',
    'מיתר',
    'מכורה',
    'מכחול',
    'מכמורת',
    'מכמנים',
    'מלאה',
    'מלילות',
    'מלכיה',
    'מנוחה',
    'מנוף',
    'מנות',
    'מנחמיה',
    'מנרה',
    'מנשית זבדה',
    'מסד',
    'מסדה',
    'מסילות',
    'מסילת ציון',
    'מסלול',
    'מסעדה',
    'מסעודין אל-עזאזמה',
    'מעברות',
    'מעגלים',
    'מעגן',
    'מעגן מיכאל',
    'מעוז חיים',
    'מעון',
    'מעונה',
    'מעיליא',
    'מעין ברוך',
    'מעין צבי',
    'מעלה אדומים',
    'מעלה אפרים',
    'מעלה גלבוע',
    'מעלה גמלא',
    'מעלה החמישה',
    'מעלה לבונה',
    'מעלה מכמש',
    'מעלה עירון',
    'מעלה עמוס',
    'מעלות-תרשיחא',
    'מענית',
    'מעש',
    'מפלסים',
    'מצדות יהודה',
    'מצובה',
    'מצליח',
    'מצפה',
    'מצפה אבי"ב',
    'מצפה אילן',
    'מצפה יריחו',
    'מצפה נטופה',
    'מצפה רמון',
    'מצפה שלם',
    'מצר',
    'מקווה ישראל',
    'מרגליות',
    'מרום גולן',
    'מרחב עם',
    'מרחביה (מושב)',
    'מרחביה (קיבוץ)',
    'מרכז שפירא',
    'משאבי שדה',
    'משגב דב',
    'משגב עם',
    'משהד',
    'משואה',
    'משואות יצחק',
    'משכיות',
    'משמר איילון',
    'משמר דוד',
    'משמר הירדן',
    'משמר הנגב',
    'משמר העמק',
    'משמר השבעה',
    'משמר השרון',
    'משמר יהודה',
    'משמרות',
    'משמרת',
    'משען',
    'מתן',
    'מתת',
    'מתתיהו',
    'נאות גולן',
    'נאות הכיכר',
    'נאות מרדכי',
    'נאות סמדר',
    'נאעורה',
    'נבטים',
    'נגבה',
    'נגוהות',
    'נהורה',
    'נהלל',
    'נהריה',
    'נוב',
    'נוגה',
    'נוה צוף',
    'נווה',
    'נווה אבות',
    'נווה אור',
    'נווה אטי"ב',
    'נווה אילן',
    'נווה איתן',
    'נווה דניאל',
    'נווה זוהר',
    'נווה זיו',
    'נווה חריף',
    'נווה ים',
    'נווה ימין',
    'נווה ירק',
    'נווה מבטח',
    'נווה מיכאל',
    'נווה שלום',
    'נועם',
    'נוף איילון',
    'נוף הגליל',
    'נופים',
    'נופית',
    'נופך',
    'נוקדים',
    'נורדיה',
    'נורית',
    'נחושה',
    'נחל עוז',
    'נחלה',
    'נחליאל',
    'נחלים',
    'נחם',
    'נחף',
    'נחשולים',
    'נחשון',
    'נחשונים',
    'נטועה',
    'נטור',
    'נטע',
    'נטעים',
    'נטף',
    'ניין',
    'ניל"י',
    'ניצן',
    "ניצן ב'",
    'ניצנה (קהילת חינוך)',
    'ניצני סיני',
    'ניצני עוז',
    'ניצנים',
    'ניר אליהו',
    'ניר בנים',
    'ניר גלים',
    'ניר דוד (תל עמל)',
    'ניר ח"ן',
    'ניר יפה',
    'ניר יצחק',
    'ניר ישראל',
    'ניר משה',
    'ניר עוז',
    'ניר עם',
    'ניר עציון',
    'ניר עקיבא',
    'ניר צבי',
    'נירים',
    'נירית',
    'נמרוד',
    'נס הרים',
    'נס עמים',
    'נס ציונה',
    'נעורים',
    'נעלה',
    'נעמ"ה',
    'נען',
    'נערן',
    'נצאצרה (שבט)',
    'נצר חזני',
    'נצר סרני',
    'נצרת',
    'נשר',
    'נתיב הגדוד',
    'נתיב הל"ה',
    'נתיב העשרה',
    'נתיב השיירה',
    'נתיבות',
    'נתניה',
    "סאג'ור",
    'סאסא',
    'סביון',
    'סגולה',
    'סואעד (חמרייה)',
    'סואעד (כמאנה) (שבט)',
    'סולם',
    'סוסיה',
    'סופה',
    "סח'נין",
    'סייד (שבט)',
    'סלמה',
    'סלעית',
    'סמר',
    'סנסנה',
    'סעד',
    'סעוה',
    'סער',
    'ספיר',
    'סתריה',
    "ע'ג'ר",
    'עבדון',
    'עברון',
    'עגור',
    'עדי',
    'עדנים',
    'עוזה',
    'עוזייר',
    'עולש',
    'עומר',
    'עופר',
    'עופרה',
    'עוצם',
    'עוקבי (בנו עוקבה)',
    'עזוז',
    'עזר',
    'עזריאל',
    'עזריה',
    'עזריקם',
    'עטאוונה (שבט)',
    'עטרת',
    'עידן',
    'עיילבון',
    'עיינות',
    'עילוט',
    'עין איילה',
    'עין אל-אסד',
    'עין גב',
    'עין גדי',
    'עין דור',
    'עין הבשור',
    'עין הוד',
    'עין החורש',
    'עין המפרץ',
    'עין הנצי"ב',
    'עין העמק',
    'עין השופט',
    'עין השלושה',
    'עין ורד',
    'עין זיוון',
    'עין חוד',
    'עין חצבה',
    'עין חרוד (איחוד)',
    'עין חרוד (מאוחד)',
    'עין יהב',
    'עין יעקב',
    'עין כרם-בי"ס חקלאי',
    'עין כרמל',
    'עין מאהל',
    'עין נקובא',
    'עין עירון',
    'עין צורים',
    'עין קנייא',
    'עין ראפה',
    'עין שמר',
    'עין שריד',
    'עין תמר',
    'עינת',
    'עיר אובות',
    'עכו',
    'עלומים',
    'עלי',
    'עלי זהב',
    'עלמה',
    'עלמון',
    'עמוקה',
    'עמיחי',
    'עמינדב',
    'עמיעד',
    'עמיעוז',
    'עמיקם',
    'עמיר',
    'עמנואל',
    'עמקה',
    'ענב',
    'עספיא',
    'עפולה',
    'עצמון שגב',
    'עראבה',
    'עראמשה',
    'ערב אל נעים',
    'ערד',
    'ערוגות',
    'ערערה',
    'ערערה-בנגב',
    'עשהאל',
    'עשרת',
    'עתלית',
    'עתניאל',
    'פארן',
    'פדואל',
    'פדויים',
    'פדיה',
    'פוריה - כפר עבודה',
    'פוריה - נווה עובד',
    'פוריה עילית',
    'פוריידיס',
    'פורת',
    'פטיש',
    'פלך',
    'פלמחים',
    'פני חבר',
    'פסגות',
    'פסוטה',
    'פעמי תש"ז',
    'פצאל',
    'פקיעין (בוקייעה)',
    'פקיעין חדשה',
    'פרדס חנה-כרכור',
    'פרדסיה',
    'פרוד',
    'פרזון',
    'פרי גן',
    'פתח תקווה',
    'פתחיה',
    'צאלים',
    'צביה',
    'צבעון',
    'צובה',
    'צוחר',
    'צופיה',
    'צופים',
    'צופית',
    'צופר',
    'צוקי ים',
    'צוקים',
    'צור הדסה',
    'צור יצחק',
    'צור משה',
    'צור נתן',
    'צוריאל',
    'צורית',
    'ציפורי',
    'צלפון',
    'צנדלה',
    'צפריה',
    'צפרירים',
    'צפת',
    'צרופה',
    'צרעה',
    'קבועה (שבט)',
    'קבוצת יבנה',
    'קדומים',
    'קדימה-צורן',
    'קדמה',
    'קדמת צבי',
    'קדר',
    'קדרון',
    'קדרים',
    'קודייראת א-צאנע(שבט)',
    'קוואעין (שבט)',
    'קוממיות',
    'קורנית',
    'קטורה',
    'קיסריה',
    'קלחים',
    'קליה',
    'קלנסווה',
    'קלע',
    'קציר',
    'קצר א-סר',
    'קצרין',
    'קרית אונו',
    'קרית ארבע',
    'קרית אתא',
    'קרית ביאליק',
    'קרית גת',
    'קרית טבעון',
    'קרית ים',
    'קרית יערים',
    'קרית יערים(מוסד)',
    'קרית מוצקין',
    'קרית מלאכי',
    'קרית נטפים',
    'קרית ענבים',
    'קרית עקרון',
    'קרית שלמה',
    'קרית שמונה',
    'קרני שומרון',
    'קשת',
    'ראמה',
    'ראס אל-עין',
    'ראס עלי',
    'ראש העין',
    'ראש פינה',
    'ראש צורים',
    'ראשון לציון',
    'רבבה',
    'רבדים',
    'רביבים',
    'רביד',
    'רגבה',
    'רגבים',
    'רהט',
    'רווחה',
    'רוויה',
    'רוח מדבר',
    'רוחמה',
    'רומאנה',
    'רומת הייב',
    'רועי',
    'רותם',
    'רחוב',
    'רחובות',
    'רחלים',
    'ריחאניה',
    'ריחן',
    'ריינה',
    'רימונים',
    'רינתיה',
    'רכסים',
    'רם-און',
    'רמות',
    'רמות השבים',
    'רמות מאיר',
    'רמות מנשה',
    'רמות נפתלי',
    'רמלה',
    'רמת גן',
    'רמת דוד',
    'רמת הכובש',
    'רמת השופט',
    'רמת השרון',
    'רמת טראמפ',
    'רמת יוחנן',
    'רמת ישי',
    'רמת מגשימים',
    'רמת צבי',
    'רמת רזיאל',
    'רמת רחל',
    'רנן',
    'רעים',
    'רעננה',
    'רקפת',
    'רשפון',
    'רשפים',
    'רתמים',
    'שאר ישוב',
    'שבי דרום',
    'שבי ציון',
    'שבי שומרון',
    'שבלי - אום אל-גנם',
    'שגב-שלום',
    'שדה אילן',
    'שדה אליהו',
    'שדה אליעזר',
    'שדה בוקר',
    'שדה דוד',
    'שדה ורבורג',
    'שדה יואב',
    'שדה יעקב',
    'שדה יצחק',
    'שדה משה',
    'שדה נחום',
    'שדה נחמיה',
    'שדה ניצן',
    'שדה עוזיהו',
    'שדה צבי',
    'שדות ים',
    'שדות מיכה',
    'שדי אברהם',
    'שדי חמד',
    'שדי תרומות',
    'שדמה',
    'שדמות דבורה',
    'שדמות מחולה',
    'שדרות',
    'שואבה',
    'שובה',
    'שובל',
    'שוהם',
    'שומרה',
    'שומריה',
    'שוקדה',
    'שורש',
    'שורשים',
    'שושנת העמקים',
    'שזור',
    'שחר',
    'שחרות',
    'שחרית',
    'שיבולים',
    'שיזף',
    'שיטים',
    "שייח' דנון",
    'שילה',
    'שילת',
    'שכניה',
    'שלווה',
    'שלווה במדבר',
    'שלוחות',
    'שלומי',
    'שלומית',
    'שמיר',
    'שמעה',
    'שמרת',
    'שמשית',
    'שני',
    'שניר',
    'שעב',
    'שעל',
    'שעלבים',
    'שער אפרים',
    'שער הגולן',
    'שער העמקים',
    'שער מנשה',
    'שער שומרון',
    'שפיים',
    'שפיר',
    'שפר',
    'שפרעם',
    'שקד',
    'שקף',
    'שרונה',
    'שריגים (לי-און)',
    'שריד',
    'שרשרת',
    'שתולה',
    'שתולים',
    'תאשור',
    'תדהר',
    'תובל',
    'תומר',
    'תושיה',
    'תימורים',
    'תירוש',
    'תל אביב - יפו',
    'תל יוסף',
    'תל יצחק',
    'תל מונד',
    'תל עדשים',
    'תל ציון',
    'תל קציר',
    'תל שבע',
    'תל תאומים',
    'תלם',
    'תלמי אליהו',
    'תלמי אלעזר',
    'תלמי ביל"ו',
    'תלמי יוסף',
    'תלמי יחיאל',
    'תלמי יפה',
    'תלמים',
    'תמרת',
    'תנובות',
    'תעוז',
    'תפרח',
    'תקומה',
    'תקוע',
    'תראבין א-צאנע (שבט)',
    'תראבין א-צאנע(ישוב)',
    'תרום',
  ],
  en: [
    "A'Sam",
    'Abbirim',
    'Abu Abdun',
    'Abu Ammar',
    'Abu Amre',
    'Abu Ghosh',
    "Abu Juwei'Id",
    'Abu Qureinat',
    'Abu Qureinat',
    "Abu Rubei'A",
    'Abu Ruqayyeq',
    'Abu Sinan',
    'Abu Sureihan',
    'Abu Tulul',
    'Adamit',
    'Adanim',
    'Adderet',
    'Addirim',
    'Adi',
    'Adora',
    'Afeinish',
    'Afeq',
    'Afiq',
    'Afiqim',
    'Afula',
    'Agur',
    'Ahawa',
    "Ahi'Ezer",
    'Ahihud',
    'Ahisamakh',
    'Ahituv',
    'Ahuzzam',
    'Ahuzzat Baraq',
    'Akko',
    'Al Sayyid',
    'Al-Aryan',
    'Al-Azy',
    'Ale Zahav',
    'Alfe Menashe',
    'Allon Hagalil',
    'Allon Shevut',
    'Allone Abba',
    'Allone Habashan',
    'Allone Yizhaq',
    'Allonim',
    'Alma',
    'Almagor',
    'Almog',
    'Almon',
    'Alumim',
    'Alumma',
    'Alummot',
    'Amazya',
    'Amir',
    'Amirim',
    "Ammi'Ad",
    "Ammi'Oz",
    'Ammihay',
    'Amminadav',
    'Ammiqam',
    'Amnun',
    'Amqa',
    'Amuqqa',
    "Ani'Am",
    "Ar'Ara",
    "Ar'Ara-Banegev",
    'Arad',
    'Aramsha',
    'Arbel',
    'Argaman',
    "Ari'El",
    'Arrab Al Naim',
    'Arrabe',
    'Arsuf',
    'Arugot',
    "Asa'El",
    'Asad',
    'Asefar',
    'Aseret',
    'Ashalim',
    'Ashdod',
    "Ashdot Ya'Aqov(Ihud)",
    "Ashdot Ya'Aqov(Me'Uh",
    'Asherat',
    'Ashqelon',
    'Atawne',
    'Ateret',
    'Atlit',
    'Atrash',
    'Atsmon-Segev',
    'Avdon',
    'Avenat',
    "Avi'El",
    "Avi'Ezer",
    'Avigayil',
    'Avigedor',
    'Avihayil',
    'Avital',
    'Avivim',
    'Avne Etan',
    'Avne Hefez',
    'Avshalom',
    'Avtalyon',
    'Ayanot',
    'Ayyelet Hashahar',
    'Azarya',
    'Azor',
    "Azri'El",
    'Azriqam',
    'Bahan',
    'Balfuriyya',
    'Baqa Al-Gharbiyye',
    'Bar Giyyora',
    'Bar Yohay',
    "Bar'Am",
    'Baraq',
    'Bareqet',
    'Barqan',
    'Barqay',
    'Basma',
    "Basmat Tab'Un",
    'Bat Ayin',
    'Bat Hadar',
    'Bat Hefer',
    'Bat Hen',
    'Bat Shelomo',
    'Bat Yam',
    'Bazra',
    "Be'Er Milka",
    "Be'Er Ora",
    "Be'Er Sheva",
    "Be'Er Tuveya",
    "Be'Er Ya'Aqov",
    "Be'Eri",
    "Be'Erot Yizhaq",
    "Be'Erotayim",
    'Beer Gannim',
    'Beit Jann',
    'Ben Ammi',
    'Ben Shemen (Moshav)',
    "Ben Shemen(K.No'Ar)",
    'Ben Zakkay',
    'Benaya',
    'Bene Atarot',
    'Bene Ayish',
    'Bene Beraq',
    'Bene Darom',
    'Bene Deror',
    'Bene Nezarim',
    "Bene Re'Em",
    'Bene Yehuda',
    'Bene Ziyyon',
    "Beqa'Ot",
    'Beqoa',
    'Berakha',
    'Berekhya',
    'Beror Hayil',
    'Berosh',
    'Bet Alfa',
    'Bet Arif',
    'Bet Arye',
    'Bet Berl',
    'Bet Dagan',
    'Bet El',
    "Bet El'Azari",
    'Bet Ezra',
    "Bet Gamli'El",
    'Bet Guvrin',
    'Bet Haarava',
    'Bet Haemeq',
    'Bet Hagaddi',
    'Bet Halevi',
    'Bet Hanan',
    'Bet Hananya',
    'Bet Hashitta',
    'Bet Hashmonay',
    'Bet Herut',
    'Bet Hillel',
    'Bet Hilqiyya',
    'Bet Hogla',
    'Bet Horon',
    'Bet Lehem Hagelilit',
    "Bet Me'Ir",
    'Bet Nehemya',
    'Bet Neqofa',
    'Bet Nir',
    'Bet Oren',
    'Bet Oved',
    'Bet Qama',
    'Bet Qeshet',
    'Bet Rabban',
    'Bet Rimmon',
    "Bet She'An",
    "Bet She'Arim",
    'Bet Shemesh',
    'Bet Shiqma',
    "Bet Uzzi'El",
    'Bet Yannay',
    'Bet Yehoshua',
    'Bet Yizhaq-Sh. Hefer',
    'Bet Yosef',
    'Bet Zayit',
    'Bet Zeid',
    'Bet Zera',
    'Bet Zevi',
    'Betar Illit',
    'Bezet',
    'Bi Ne',
    'Binyamina',
    'Bir El-Maksur',
    'Bir Hadage',
    'Biriyya',
    'Bitan Aharon',
    'Bitha',
    'Bizzaron',
    'Bne Dkalim',
    'Brukhin',
    "Bu'Eine-Nujeidat",
    "Buq'Ata",
    'Burgeta',
    'Bustan Hagalil',
    'Dabburye',
    'Dafna',
    'Dahi',
    'Daliyat Al-Karmel',
    'Daliyya',
    'Dalton',
    'Dan',
    'Daverat',
    'Deganya Alef',
    'Deganya Bet',
    'Deir Al-Asad',
    'Deir Hanna',
    'Deir Rafat',
    'Demeide',
    'Deqel',
    "Derig'At",
    'Devora',
    'Dimona',
    'Dishon',
    'Dolev',
    'Dor',
    'Dorot',
    'Dovev',
    'Dvir',
    'Efrat',
    'Eilabun',
    'Ein Al-Asad',
    'Ein Hod',
    'Ein Mahel',
    'Ein Naqquba',
    'Ein Qiniyye',
    'Ein Rafa',
    "El'Ad",
    "El'Azar",
    'El-Rom',
    'Elat',
    'Eli',
    'Eli-Ad',
    'Eliav',
    'Elifaz',
    'Elifelet',
    'Elishama',
    'Elon',
    'Elon More',
    'Elot',
    'Elqana',
    'Elqosh',
    'Elyakhin',
    'Elyaqim',
    'Elyashiv',
    'Emunim',
    'En Ayyala',
    'En Dor',
    'En Gedi',
    'En Gev',
    'En Habesor',
    'En Haemeq',
    'En Hahoresh',
    'En Hamifraz',
    'En Hanaziv',
    'En Harod (Ihud)',
    "En Harod(Me'Uhad)",
    'En Hashelosha',
    'En Hashofet',
    'En Hazeva',
    'En Hod',
    'En Iron',
    "En Karem-B.S.Haqla'I",
    'En Karmel',
    'En Sarid',
    'En Shemer',
    'En Tamar',
    'En Wered',
    "En Ya'Aqov",
    'En Yahav',
    'En Ziwan',
    'En Zurim',
    'Enat',
    'Enav',
    'Erez',
    'Eshbol',
    'Eshel Hanasi',
    'Eshhar',
    'Eshkolot',
    "Eshta'Ol",
    'Etan',
    'Etanim',
    'Etgar',
    'Even Menahem',
    'Even Sappir',
    "Even Shemu'El",
    'Even Yehuda',
    "Even Yizhaq(Gal'Ed)",
    'Evron',
    'Eyal',
    'Ezer',
    'Ezuz',
    'Fassuta',
    'Fureidis',
    "Ga'Ash",
    "Ga'Ton",
    'Gadish',
    'Gadot',
    "Gal'On",
    'Gan Hadarom',
    'Gan Hashomeron',
    'Gan Hayyim',
    'Gan Ner',
    'Gan Shelomo',
    "Gan Shemu'El",
    'Gan Soreq',
    'Gan Yavne',
    'Gan Yoshiyya',
    'Ganne Am',
    'Ganne Hadar',
    'Ganne Modiin',
    'Ganne Tal',
    'Ganne Tiqwa',
    'Ganne Yohanan',
    'Gannot',
    'Gannot Hadar',
    'Gat Rimmon',
    'Gat(Qibbuz)',
    'Gazit',
    "Ge'A",
    "Ge'Alya",
    "Ge'Ule Teman",
    "Ge'Ulim",
    'Gedera',
    'Gefen',
    'Gelil Yam',
    'Gerofit',
    'Gesher',
    'Gesher Haziw',
    'Geshur',
    'Geva',
    'Geva Binyamin',
    'Geva Karmel',
    "Geva'Ot Bar",
    "Gevar'Am",
    'Gevat',
    'Gevim',
    'Gevulot',
    'Gezer',
    'Ghajar',
    'Gibbeton',
    "Gid'Ona",
    'Gilat',
    'Gilgal',
    'Gilon',
    'Gimzo',
    'Ginnaton',
    'Ginnegar',
    'Ginnosar',
    'Gitta',
    'Gittit',
    "Giv'At Avni",
    "Giv'At Brenner",
    "Giv'At Ela",
    "Giv'At Hashelosha",
    "Giv'At Hayyim (Ihud)",
    "Giv'At Hayyim(Me'Uha",
    "Giv'At Hen",
    "Giv'At Koah",
    "Giv'At Nili",
    "Giv'At Oz",
    "Giv'At Shappira",
    "Giv'At Shemesh",
    "Giv'At Shemu'El",
    "Giv'At Ye'Arim",
    "Giv'At Yesha'Yahu",
    "Giv'At Yo'Av",
    "Giv'At Ze'Ev",
    "Giv'Atayim",
    "Giv'Ati",
    "Giv'Olim",
    "Giv'On Hahadasha",
    "Giv'Ot Eden",
    "Giv'Ot Haro'E",
    'Gizo',
    'Gonen',
    'Goren',
    'Gornot Hagalil',
    'Habonim',
    'Had-Nes',
    'Hadar Am',
    'Hadera',
    'Hadid',
    'Hafez Hayyim',
    'Haggai',
    'Hagor',
    'Hagosherim',
    'Hahoterim',
    'Haifa',
    'Haluz',
    "Hama'Pil",
    'Hamadya',
    'Hamam',
    'Hamra',
    'Hanita',
    'Hannaton',
    "Hanni'El",
    'Haogen',
    'Haon',
    'Har Adar',
    'Har Amasa',
    'Har Gillo',
    "Har'El",
    'Hararit',
    'Harashim',
    'Harduf',
    'Harish',
    'Haruzim',
    "Hashmona'Im",
    'Hasolelim',
    'Haspin',
    'Havazzelet Hasharon',
    'Hawashla',
    'Hayogev',
    'Hazav',
    'Hazerim',
    'Hazeva',
    'Hazon',
    'Hazor Hagelilit',
    'Hazor-Ashdod',
    "Hazore'Im",
    'Hazorea',
    'Hefzi-Bah',
    'Helez',
    'Hemed',
    "Herev Le'Et",
    'Hermesh',
    'Herut',
    'Herzeliyya',
    'Hever',
    'Hevron',
    'Hibbat Ziyyon',
    'Hilla',
    'Hinnanit',
    'Hod Hasharon',
    'Hodayot',
    'Hodiyya',
    'Hofit',
    'Hogla',
    'Holit',
    'Holon',
    'Horeshim',
    'Hosen',
    "Hosha'Aya",
    'Hujeirat (Dahra)',
    'Hulata',
    'Hulda',
    'Huqoq',
    'Hura',
    'Hurfeish',
    'Hussniyya',
    'Huzayyel',
    "I'Billin",
    'Ibbim',
    'Ibtin',
    'Iddan',
    'Iksal',
    'Ilaniyya',
    'Ilut',
    "Immanu'El",
    'Ir Ovot',
    'Irus',
    'Isifya',
    'Itamar',
    'Jaat',
    'Jaljulye',
    'Jerusalem',
    'Jish(Gush Halav)',
    'Jisr Az-Zarqa',
    'Judeide-Maker',
    'Julis',
    'Junnabib',
    "Ka'Abiyye-Tabbash-Ha",
    'Kabri',
    'Kabul',
    'Kaddita',
    'Kadoorie',
    'Kafar Bara',
    'Kafar Kama',
    'Kafar Kanna',
    'Kafar Manda',
    'Kafar Misr',
    'Kafar Qara',
    'Kafar Qasem',
    'Kafar Yasif',
    'Kahal',
    'Kallanit',
    'Kamanneh',
    'Kammon',
    'Kanaf',
    'Kannot',
    'Kaokab Abu Al-Hija',
    'Kare Deshe',
    'Karkom',
    'Karme Qatif',
    'Karme Yosef',
    'Karme Zur',
    'Karmel',
    "Karmi'El",
    'Karmiyya',
    'Kefar Adummim',
    'Kefar Ahim',
    'Kefar Aviv',
    'Kefar Avoda',
    'Kefar Azza',
    'Kefar Barukh',
    'Kefar Bialik',
    'Kefar Bilu',
    'Kefar Bin Nun',
    'Kefar Blum',
    'Kefar Daniyyel',
    'Kefar Ezyon',
    'Kefar Gallim',
    "Kefar Gid'On",
    "Kefar Gil'Adi",
    'Kefar Glikson',
    'Kefar Habad',
    'Kefar Hahoresh',
    'Kefar Hamakkabi',
    'Kefar Hanagid',
    'Kefar Hananya',
    'Kefar Hanasi',
    "Kefar Hano'Ar Hadati",
    'Kefar Haoranim',
    'Kefar Harif',
    "Kefar Haro'E",
    'Kefar Haruv',
    'Kefar Hasidim Alef',
    'Kefar Hasidim Bet',
    'Kefar Hayyim',
    'Kefar Hess',
    'Kefar Hittim',
    'Kefar Hoshen',
    'Kefar Kish',
    'Kefar Malal',
    'Kefar Masaryk',
    'Kefar Maymon',
    'Kefar Menahem',
    'Kefar Monash',
    'Kefar Mordekhay',
    'Kefar Netter',
    'Kefar Pines',
    'Kefar Rosh Haniqra',
    'Kefar Rozenwald(Zar.',
    'Kefar Ruppin',
    'Kefar Rut',
    'Kefar Sava',
    'Kefar Shammay',
    'Kefar Shemaryahu',
    "Kefar Shemu'El",
    'Kefar Silver',
    'Kefar Sirkin',
    'Kefar Szold',
    'Kefar Tappuah',
    'Kefar Tavor',
    'Kefar Truman',
    'Kefar Uriyya',
    'Kefar Vitkin',
    'Kefar Warburg',
    'Kefar Weradim',
    "Kefar Ya'Bez",
    'Kefar Yehezqel',
    'Kefar Yehoshua',
    'Kefar Yona',
    'Kefar Zetim',
    'Kefar Zoharim',
    'Kelil',
    'Kemehin',
    'Keramim',
    'Kerem Ben Shemen',
    'Kerem Ben Zimra',
    'Kerem Beyavne',
    'Kerem Maharal',
    'Kerem Shalom',
    'Kesalon',
    'Khawaled',
    'Khawaled',
    'Kinneret(Moshava)',
    'Kinneret(Qevuza)',
    'Kishor',
    'Kisra-Sumei',
    'Kissufim',
    'Kochlea',
    'Kokhav Hashahar',
    "Kokhav Mikha'El",
    "Kokhav Ya'Aqov",
    "Kokhav Ya'Ir",
    'Korazim',
    'Kuseife',
    'Lahav',
    'Lahavot Habashan',
    'Lahavot Haviva',
    'Lakhish',
    'Lappid',
    'Lappidot',
    'Laqye',
    'Lavi',
    'Lavon',
    'Lehavim',
    'Li-On',
    'Liman',
    'Livnim',
    'Lod',
    "Lohame Hageta'Ot",
    'Lotan',
    'Lotem',
    'Luzit',
    "Ma'Agan",
    "Ma'Agan Mikha'El",
    "Ma'Ale Adummim",
    "Ma'Ale Amos",
    "Ma'Ale Efrayim",
    "Ma'Ale Gamla",
    "Ma'Ale Gilboa",
    "Ma'Ale Hahamisha",
    "Ma'Ale Iron",
    "Ma'Ale Levona",
    "Ma'Ale Mikhmas",
    "Ma'Alot-Tarshiha",
    "Ma'Anit",
    "Ma'As",
    "Ma'Barot",
    "Ma'Galim",
    "Ma'On",
    "Ma'Or",
    "Ma'Oz Hayyim",
    "Ma'Yan Barukh",
    "Ma'Yan Zevi",
    "Mabbu'Im",
    'Magen',
    "Magen Sha'Ul",
    'Maggal',
    'Magshimim',
    'Mahanayim',
    'Mahane Bildad',
    'Mahane Hilla',
    'Mahane Miryam',
    'Mahane Tali',
    'Mahane Tel Nof',
    'Mahane Yafa',
    'Mahane Yattir',
    'Mahane Yehudit',
    'Mahane Yokhved',
    'Mahseya',
    'Majd Al-Kurum',
    'Majdal Shams',
    'Makchul',
    'Malkiyya',
    'Manof',
    'Manot',
    'Manshiyyet Zabda',
    'Margaliyyot',
    "Mas'Ade",
    "Mas'Udin Al-'Azazme",
    "Mash'Abbe Sade",
    "Mash'En",
    'Maskiyyot',
    'Maslul',
    'Massad',
    'Massada',
    "Massu'A",
    'Massuot Yizhaq',
    'Matta',
    'Mattan',
    'Mattat',
    'Mattityahu',
    "Mavqi'Im",
    'Mazkeret Batya',
    'Mazliah',
    'Mazor',
    "Mazra'A",
    'Mazzuva',
    'Me Ammi',
    "Me'Ir Shefeya",
    "Me'Ona",
    'Mefallesim',
    'Megadim',
    'Megiddo',
    'Mehola',
    'Meiser',
    'Mekhora',
    "Mele'A",
    'Melilot',
    'Menahemya',
    'Mennara',
    'Menuha',
    'Merav',
    'Merhav Am',
    'Merhavya(Moshav)',
    'Merhavya(Qibbuz)',
    'Merkaz Shappira',
    'Merom Golan',
    'Meron',
    'Meshar',
    'Meshhed',
    'Mesillat Ziyyon',
    'Mesillot',
    'Metal',
    'Metar',
    'Metav',
    'Metula',
    'Mevasseret Ziyyon',
    'Mevo Betar',
    'Mevo Dotan',
    'Mevo Hamma',
    'Mevo Horon',
    "Mevo Modi'Im",
    "Mevo'Ot Yam",
    "Mevo'Ot Yeriho",
    'Mezadot Yehuda',
    'Mezar',
    'Mezer',
    "Mi'Elya",
    'Midrakh Oz',
    'Midreshet Ben Gurion',
    'Midreshet Ruppin',
    'Migdal',
    'Migdal Haemeq',
    'Migdal Oz',
    'Migdalim',
    'Mikhmannim',
    'Mikhmoret',
    "Miqwe Yisra'El",
    'Misgav Am',
    'Misgav Dov',
    'Mishmar Ayyalon',
    'Mishmar Dawid',
    'Mishmar Haemeq',
    'Mishmar Hanegev',
    'Mishmar Hasharon',
    "Mishmar Hashiv'A",
    'Mishmar Hayarden',
    'Mishmar Yehuda',
    'Mishmarot',
    'Mishmeret',
    'Mitspe Ilan',
    'Mivtahim',
    'Mizpa',
    'Mizpe Aviv',
    'Mizpe Netofa',
    'Mizpe Ramon',
    'Mizpe Shalem',
    'Mizpe Yeriho',
    'Mizra',
    "Modi'In Illit",
    "Modi'In-Makkabbim-Re",
    'Moledet',
    'Moran',
    'Moreshet',
    'Moza Illit',
    'Mughar',
    'Muqeible',
    "Na'Ale",
    "Na'An",
    "Na'Aran",
    "Na'Ura",
    'Naama',
    'Nahal Eshbal',
    'Nahal Hemdat',
    'Nahal Oz',
    'Nahal Shittim',
    'Nahala',
    'Nahalal',
    "Nahali'El",
    'Naham',
    'Nahariyya',
    'Nahef',
    'Nahsholim',
    'Nahshon',
    'Nahshonim',
    'Nasasra',
    'Nataf',
    'Natur',
    'Nave',
    'Nazareth',
    "Ne'Ot Golan",
    "Ne'Ot Hakikkar",
    "Ne'Ot Mordekhay",
    "Ne'Urim",
    'Negba',
    'Negohot',
    'Nehalim',
    'Nehora',
    'Nehusha',
    'Nein',
    'Nes Ammim',
    'Nes Harim',
    'Nes Ziyyona',
    'Nesher',
    'Neta',
    "Neta'Im",
    'Netanya',
    'Netiv Haasara',
    'Netiv Hagedud',
    'Netiv Halamed-He',
    'Netiv Hashayyara',
    'Netivot',
    "Netu'A",
    'Nevatim',
    'Neve Tsuf',
    'Newe Ativ',
    'Newe Avot',
    'Newe Daniyyel',
    'Newe Etan',
    'Newe Harif',
    'Newe Ilan',
    "Newe Mikha'El",
    'Newe Mivtah',
    'Newe Shalom',
    'Newe Ur',
    'Newe Yam',
    'Newe Yamin',
    'Newe Yaraq',
    'Newe Ziv',
    'Newe Zohar',
    'Nezer Hazzani',
    'Nezer Sereni',
    'Nili',
    'Nimrod',
    'Nir Am',
    'Nir Aqiva',
    'Nir Banim',
    'Nir Dawid (Tel Amal)',
    'Nir Eliyyahu',
    'Nir Ezyon',
    'Nir Gallim',
    'Nir Hen',
    'Nir Moshe',
    'Nir Oz',
    'Nir Yafe',
    "Nir Yisra'El",
    'Nir Yizhaq',
    'Nir Zevi',
    'Nirim',
    'Nirit',
    'Nizzan',
    'Nizzan B',
    'Nizzana (Qehilat Hin',
    'Nizzane Oz',
    'Nizzane Sinay',
    'Nizzanim',
    "No'Am",
    'Nof Ayyalon',
    'Nof Hagalil',
    'Nofekh',
    'Nofim',
    'Nofit',
    'Nogah',
    'Noqedim',
    'Nordiyya',
    'Nov',
    'Nurit',
    'Odem',
    'Ofaqim',
    'Ofer',
    'Ofra',
    'Ohad',
    'Olesh',
    'Omen',
    'Omer',
    'Omez',
    'Or Aqiva',
    'Or Haganuz',
    'Or Haner',
    'Or Yehuda',
    'Ora',
    'Oranim',
    'Oranit',
    'Orot',
    'Ortal',
    "Otni'El",
    'Ozem',
    "Pa'Ame Tashaz",
    'Palmahim',
    'Paran',
    'Pardes Hanna-Karkur',
    'Pardesiyya',
    'Parod',
    'Pattish',
    'Pedaya',
    "Pedu'El",
    'Peduyim',
    'Pelekh',
    'Pene Hever',
    "Peqi'In (Buqei'A)",
    "Peqi'In Hadasha",
    'Perazon',
    'Peri Gan',
    'Pesagot',
    'Petah Tiqwa',
    'Petahya',
    "Peza'El",
    'Porat',
    'Poriyya Illit',
    'Poriyya-Kefar Avoda',
    'Poriyya-Newe Oved',
    "Qabbo'A",
    'Qaddarim',
    'Qadima-Zoran',
    'Qalansawe',
    'Qalya',
    'Qarne Shomeron',
    'Qasr Al-Sir',
    "Qawa'In",
    'Qazir',
    'Qazrin',
    'Qedar',
    'Qedma',
    'Qedumim',
    'Qela',
    'Qelahim',
    'Qesariyya',
    'Qeshet',
    'Qetura',
    'Qevuzat Yavne',
    'Qidmat Zevi',
    'Qidron',
    'Qiryat Anavim',
    'Qiryat Arba',
    'Qiryat Atta',
    'Qiryat Bialik',
    'Qiryat Eqron',
    'Qiryat Gat',
    "Qiryat Mal'Akhi",
    'Qiryat Motzkin',
    'Qiryat Netafim',
    'Qiryat Ono',
    'Qiryat Shelomo',
    'Qiryat Shemona',
    "Qiryat Tiv'On",
    'Qiryat Yam',
    "Qiryat Ye'Arim",
    "Qiryat Ye'Arim(Insti",
    'Qomemiyyut',
    'Qoranit',
    'Qudeirat As-Sani',
    "Ra'Anana",
    'Rahat',
    'Ram-On',
    'Ramat Dawid',
    'Ramat Gan',
    'Ramat Hakovesh',
    'Ramat Hasharon',
    'Ramat Hashofet',
    'Ramat Magshimim',
    'Ramat Rahel',
    "Ramat Razi'El",
    'Ramat Yishay',
    'Ramat Yohanan',
    'Ramat Zevi',
    'Rame',
    'Ramla',
    'Ramot',
    'Ramot Hashavim',
    "Ramot Me'Ir",
    'Ramot Menashe',
    'Ramot Naftali',
    'Rannen',
    'Raqefet',
    'Ras Al-Ein',
    'Ras Ali',
    'Ravid',
    "Re'Im",
    'Regavim',
    'Regba',
    'Rehan',
    'Rehelim',
    'Rehov',
    'Rehovot',
    'Reihaniyye',
    'Reine',
    'Rekhasim',
    'Reshafim',
    'Retamim',
    'Revadim',
    'Revava',
    'Revivim',
    'Rewaha',
    'Rewaya',
    'Rimmonim',
    'Rinnatya',
    'Rishon Leziyyon',
    'Rishpon',
    "Ro'I",
    'Rosh Haayin',
    'Rosh Pinna',
    'Rosh Zurim',
    'Rotem',
    'Ruah Midbar',
    'Ruhama',
    'Rumat Heib',
    'Rummane',
    "Sa'Ad",
    "Sa'Ar",
    "Sa'Wa",
    'Sajur',
    'Sakhnin',
    "Sal'It",
    'Sallama',
    'Samar',
    'Sandala',
    'Sansana',
    'Sappir',
    'Sarid',
    'Sasa',
    'Savyon',
    "Sawa'Id (Kamane)",
    "Sawa'Id(Hamriyye)",
    'Sayyid',
    'Sede Avraham',
    'Sede Boqer',
    'Sede Dawid',
    "Sede Eli'Ezer",
    'Sede Eliyyahu',
    'Sede Hemed',
    'Sede Ilan',
    'Sede Moshe',
    'Sede Nahum',
    'Sede Nehemya',
    'Sede Nizzan',
    'Sede Terumot',
    'Sede Uzziyyahu',
    'Sede Warburg',
    "Sede Ya'Aqov",
    'Sede Yizhaq',
    "Sede Yo'Av",
    'Sede Zevi',
    'Sederot',
    'Sedot Mikha',
    'Sedot Yam',
    'Segev-Shalom',
    'Segula',
    'Senir',
    "Sha'Ab",
    "Sha'Al",
    "Sha'Alvim",
    "Sha'Ar Efrayim",
    "Sha'Ar Haamaqim",
    "Sha'Ar Hagolan",
    "Sha'Ar Menashe",
    "Sha'Ar Shomron",
    'Shadmot Devora',
    'Shadmot Mehola',
    'Shafir',
    'Shahar',
    'Shaharit',
    'Shaharut',
    'Shalva Bamidbar',
    'Shalwa',
    'Shamerat',
    'Shamir',
    'Shani',
    'Shaqed',
    'Sharona',
    'Sharsheret',
    'Shave Darom',
    'Shave Shomeron',
    'Shave Ziyyon',
    "She'Ar Yashuv",
    'Shedema',
    "Shefar'Am",
    'Shefayim',
    'Shefer',
    'Sheikh Dannun',
    'Shekhanya',
    'Shelomi',
    'Sheluhot',
    'Sheqef',
    'Shetula',
    'Shetulim',
    'Shezaf',
    'Shezor',
    'Shibbolim',
    'Shibli',
    'Shilat',
    'Shilo',
    "Shim'A",
    'Shimshit',
    'Shizzafon',
    'Shlomit',
    "Sho'Eva",
    'Shoham',
    'Shomera',
    'Shomeriyya',
    'Shoqeda',
    'Shorashim',
    'Shoresh',
    'Shoshannat Haamaqim',
    'Shoshannat Haamaqim(',
    'Shoval',
    'Shuva',
    'Sitriyya',
    'Sufa',
    'Sulam',
    'Suseya',
    "Ta'Oz",
    'Tal Shahar',
    'Tal-El',
    'Talme Bilu',
    "Talme El'Azar",
    'Talme Eliyyahu',
    'Talme Yafe',
    "Talme Yehi'El",
    'Talme Yosef',
    'Talmon',
    'Tamra',
    "Tamra (Yizre'El)",
    'Tarabin As-Sani',
    'Tarabin As-Sani',
    'Tarum',
    'Tayibe',
    'Tayibe(Baemeq)',
    "Te'Ashur",
    'Tefahot',
    'Tel Adashim',
    'Tel Aviv - Yafo',
    'Tel Mond',
    'Tel Qazir',
    'Tel Sheva',
    "Tel Te'Omim",
    'Tel Tsiyon',
    'Tel Yizhaq',
    'Tel Yosef',
    'Telalim',
    'Telamim',
    'Telem',
    'Tene',
    'Tenuvot',
    'Teqoa',
    'Tequma',
    'Tiberias',
    'Tidhar',
    'Tifrah',
    'Timmorim',
    'Timrat',
    'Tirat Karmel',
    'Tirat Yehuda',
    'Tirat Zevi',
    'Tire',
    'Tirosh',
    'Tomer',
    'Trump Heights',
    'Tuba-Zangariyye',
    "Tur'An",
    'Tushiyya',
    'Tuval',
    'Udim',
    'Umm Al-Fahm',
    'Umm Al-Qutuf',
    'Umm Batin',
    'Uqbi (Banu Uqba)',
    'Urim',
    'Usha',
    'Uza',
    'Uzeir',
    'Wardon',
    'Wered Yeriho',
    "Ya'Ad",
    "Ya'Ara",
    "Ya'El",
    'Yad Binyamin',
    'Yad Hanna',
    'Yad Hashemona',
    'Yad Mordekhay',
    'Yad Natan',
    'Yad Rambam',
    'Yafi',
    'Yafit',
    'Yagel',
    'Yagur',
    'Yahel',
    'Yakhini',
    'Yanuh-Jat',
    'Yanuv',
    'Yaqir',
    'Yaqum',
    'Yardena',
    'Yarhiv',
    'Yarqona',
    "Yas'Ur",
    'Yashresh',
    'Yated',
    'Yavne',
    "Yavne'El",
    'Yaziz',
    "Ye'Af",
    'Yedida',
    'Yedidya',
    "Yehi'Am",
    'Yehud-Monoson',
    'Yeroham',
    'Yesha',
    'Yesodot',
    "Yesud Hama'Ala",
    'Yevul',
    "Yif'At",
    'Yiftah',
    'Yinnon',
    "Yir'On",
    'Yirka',
    "Yish'I",
    'Yitav',
    'Yizhar',
    "Yizre'El",
    'Yodefat',
    'Yonatan',
    "Yoqne'Am Illit",
    "Yoqne'Am(Moshava)",
    'Yoshivya',
    'Yotvata',
    'Yuval',
    'Yuvalim',
    'Zabarga',
    'Zafririm',
    'Zafriyya',
    'Zanoah',
    'Zarzir',
    "Zavdi'El",
    "Ze'Elim",
    'Zefat',
    'Zekharya',
    'Zelafon',
    'Zemer',
    'Zerahya',
    "Zeru'A",
    'Zerufa',
    'Zetan',
    "Zikhron Ya'Aqov",
    'Zimrat',
    'Zippori',
    'Ziqim',
    "Ziv'On",
    'Zofar',
    'Zofit',
    'Zofiyya',
    'Zohar',
    'Zohar',
    "Zor'A",
    'Zova',
    'Zufin',
    'Zur Hadassa',
    'Zur Moshe',
    'Zur Natan',
    'Zur Yizhaq',
    "Zuri'El",
    'Zurit',
    'Zviyya',
  ],
};
