export const COUNTRIES = {
  he: [
    'אורוגואי',
    'איסלנד',
    'ארצות הברית',
    'צרפת',
    'רומניה',
    'אוסטריה',
    'אוסטרליה',
    'איטליה',
    'ארגנטינה',
    'בלגיה',
    'בריטניה',
    'דנמרק',
    'דרום אפריקה',
    'הולנד',
    'הרפובליקה הדומיניקנית',
    'לוקסמבורג',
    'מיאנמר',
    'נורבגיה',
    'ניו זילנד',
    'פינלנד',
    'פנמה',
    'פרו',
    "צ'ילה",
    'קולומביה',
    'קוסטה ריקה',
    'קנדה',
    'שבדיה',
    'שווייץ',
    'אל סלבדור',
    'ברזיל',
    'גואטמלה',
    'הונדורס',
    'מכסיקו',
    'אקוואדור',
    'יפן',
    'תאילנד',
    'פיליפינים',
    'נפאל',
    'קפריסין',
    "ג'מאיקה",
    'טרינידד וטובגו',
    'קוריאה',
    'אנטיגואה-ברבודה',
    'מונקו',
    'מלאווי',
    'סינגפור',
    'קובה',
    'גרמניה',
    'מלטה',
    'ברבדוס',
    "פיג'י",
    'מאלי',
    'האיטי',
    'איי הבהאמס',
    'אירלנד',
    'גרנדה',
    'סורינם',
    'פורטוגל',
    'טונגה',
    'סמואה',
    'דומיניקה',
    'פפואה ניו גיני',
    'איראן',
    "סט' לוציה",
    'מצרים',
    'בליז',
    "סט' וינסנט והגרנדינים",
    'הרפובליקה הדמוקרטית של קונגו',
    'ליבריה',
    "סט' קיטס ונביס",
    'קיריבטי',
    'טובלו',
    'לבנון',
    'ספרד',
    'חוף השנהב (קוט דיוואר)',
    'קמרון',
    'איי מרשל',
    'טוגו',
    'מיקרונזיה',
    'קניה',
    'איי שלמה',
    'הונגריה',
    'אתיופיה',
    "צ'כיה",
    'פולין',
    'בולגריה',
    'יוון',
    'רפובליקה מרכז אפריקנית',
    'קונגו',
    'אלבניה',
    'סרביה',
    'מונגוליה',
    'רוסיה',
    'אוקראינה',
    'זמביה',
    'לטביה',
    'אסטוניה',
    'הודו',
    'ליטא',
    'ליכטנשטיין',
    'סין',
    'אוזבקיסטאן',
    'קירגיסטאן',
    'ארמניה',
    "אזרביג'אן",
    "טג'קיסטאן",
    'סלובניה',
    'קזחסטאן',
    'אנגולה',
    'בלארוס',
    'ניגריה',
    'סיירה ליאונה',
    'איי סיישל',
    'גיאורגיה',
    'מולדובה',
    'בנין',
    'גמביה',
    'ניקרגואה',
    'אסוואטיני',
    'סלובקיה',
    'אריתריאה',
    'טייואן',
    'ויטנאם',
    'מוזמביק',
    'גאבון',
    'מאוריציוס',
    'קמבודיה',
    'תורכמניסטאן',
    'בורקינה פסו',
    'זימבאבווה',
    'סאו תומה ופרינציפה',
    'ואטיקאן-הכס הקדוש',
    'ונואטו',
    '"לאוס, רפובליקה דמוקרטית עממית"',
    'לסוטו',
    'מדגסקר',
    'קומורוס',
    'גינאה המשוונית',
    'נמיביה',
    'גינאה-ביסאו',
    'אנדורה',
    'קייפ ורדה',
    'אוגנדה',
    'סנגל',
    'גאנה',
    'ירדן',
    'פלאו',
    'רואנדה',
    'נאורו',
    'טנזניה',
    'בורונדי',
    'סן מרינו',
    'מקדוניה',
    'גויאנה',
    'קטר',
    'בוסניה הרצגובינה',
    'קרואטיה',
    'סרי לנקה',
    'מרוקו',
    'עומאן',
    'תוניסיה',
    "ניז'ר",
    'מזרח טימור',
    'מונטנגרו',
    'איי קוק',
    'ונצואלה',
    'תורכיה',
    'מאוריטניה',
    'דרום סודאן',
    'פרגוואי',
    'גינאה',
    "צ'אד",
    'בוליביה',
    'מאע"מ, אמירויות ערביות מאוחדות',
    'בחריין',
    'יִשְׂרָאֵל',
  ],
  en: [
    'Uruguay',
    'Iceland',
    'United States of America',
    'France',
    'Romania',
    'Austria',
    'Australia',
    'Italy',
    'Argentina',
    'Belgium',
    'United Kingdom',
    'Denmark',
    'South Africa',
    'Netherlands',
    'Dominican Republic',
    'Luxembourg',
    'Myanmar',
    'Norway',
    'New Zealand',
    'Finland',
    'Panama',
    'Peru',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Canada',
    'Sweden',
    'Switzerland',
    'El Salvador',
    'Brazil',
    'Guatemala',
    'Honduras',
    'Mexico',
    'Ecuador',
    'Japan',
    'Thailand',
    'Philippines',
    'Nepal',
    'Cyprus',
    'Jamaica',
    'Trinidad & Tobago',
    'Korea',
    'Antigua - Barbuda',
    'Monaco',
    'Malawi',
    'Singapore',
    'Cuba',
    'Germany',
    'Malta',
    'Barbados',
    'Fiji',
    'Mali',
    'Haiti',
    'Bahamas',
    'Ireland',
    'Grenada',
    'Suriname',
    'Portugal',
    'Tonga',
    'Samoa',
    'Dominica',
    'Papua New Guinea',
    'Iran',
    'St. Lucia',
    'Egypt',
    'Belize',
    'St. Vincent - The Grenadines',
    'Congo (Democratic Republic)',
    'Liberia',
    'St. Kitts and Nevis',
    'Kiribati',
    'Tuvalu',
    'Lebanon',
    'Spain',
    "Cote d'Ivoire",
    'Cameroon',
    'Marshall Islands',
    'Togo',
    'Micronesia',
    'Kenya',
    'Solomon Islands',
    'Hungary',
    'Ethiopia',
    'Czech Republic',
    'Poland',
    'Bulgaria',
    'Greece',
    'Central African Republic',
    'Congo',
    'Albania',
    'Serbia',
    'Mongolia',
    'Russian Federation',
    'Ukraine',
    'Zambia',
    'Latvia',
    'Estonia',
    'India',
    'Lithuania',
    'Liechtenstein',
    'China',
    'Uzbekistan',
    'Kyrgyzstan',
    'Armenia',
    'Azerbaijan',
    'Tajikistan',
    'Slovenia',
    'Kazakhstan',
    'Angola',
    'Belarus',
    'Nigeria',
    'Sierra Leone',
    'Seychelles',
    'Georgia',
    'Moldova',
    'Benin',
    'Gambia',
    'Nicaragua',
    'Eswatini',
    'Slovak, The Republic',
    'Eritrea',
    'Taiwan',
    'Viet Nam',
    'Mozambique',
    'Gabon',
    'Mauritius',
    'Cambodia',
    'Turkmenistan',
    'Burkina Faso',
    'Zimbabwe',
    'Sao Tome - Principe',
    'Holy See',
    'Vanuatu',
    'Laos',
    'Lesotho',
    'Madagascar',
    'Comoros',
    'Equatorial Guinea',
    'Namibia',
    'Guinea-Bissau',
    'Andorra',
    'Cape Verde',
    'Uganda',
    'Senegal',
    'Ghana',
    'Jordan',
    'Republic Of Palau',
    'Rwanda',
    'Nauru',
    'United Republic of Tanzania',
    'Burundi',
    'San Marino',
    'Macedonia (FYROM)',
    'Guyana',
    'Qatar',
    'Bosnia - Herzegovina',
    'Croatia',
    'Sri Lanka',
    'Morocco',
    'Sultanate of Oman',
    'Tunisia',
    'Niger',
    'East Timor',
    'Montenegro',
    'Cook Islands',
    'Venezuela',
    'Turkey',
    'Mauritania',
    'South Sudan',
    'Paraguay',
    'Guinea',
    'Chad',
    'Bolivia',
    'United Arab Emirates',
    'Bahrain',
    'Israel',
  ],
};
